
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using UnityEngine.SceneManagement;

public class MultiPlayerButton : MonoBehaviour
{

    public GameManager gameManager;
    //scene name we want to open
    public string sceneName = "Main";

    //the button this is attached to
    public Button button1;

    //text that could be on a UI but we want it blank
    public TMP_Text b1text;

    // Start is called before the first frame update
    void Start()
    {
      //  gameManager.multiplayer = true;

        gameManager.killScore = 0;
      //  gameManager.lives = gameManager.lives * 2;
     //   gameManager.multiplayer = true;

        // adding the listender so it can be clicked
        button1.onClick.AddListener(taskonclick);

        // setting up communication with the text value to then get rid of the text
        b1text = gameObject.GetComponentInChildren<TMP_Text>(true);
        btnValue();

     
    }

    //To load the main level
    void taskonclick()
    {
        //if (gameManager != null)
      //  {
            gameManager.killScore = 0;
        gameManager.lives = 6;
            gameManager.multiplayer = true;
           // loadScene();
         
       // }
    }


    //To blank out the autogenerated text
    public void btnValue()
    {
        b1text.text = "";
    }

   public void loadScene()
    {
        SceneManager.LoadScene(sceneName);
    }

}
